#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : gnome-boxes
Version  : 3.34.3
Release  : 8
URL      : https://download.gnome.org/sources/gnome-boxes/3.34/gnome-boxes-3.34.3.tar.xz
Source0  : https://download.gnome.org/sources/gnome-boxes/3.34/gnome-boxes-3.34.3.tar.xz
Summary  : Library for reading and writing virtual machine images in the Open Virtualization Format
Group    : Development/Tools
License  : CC-BY-2.0 LGPL-2.0 LGPL-2.1 LGPL-3.0
Requires: gnome-boxes-bin = %{version}-%{release}
Requires: gnome-boxes-data = %{version}-%{release}
Requires: gnome-boxes-lib = %{version}-%{release}
Requires: gnome-boxes-libexec = %{version}-%{release}
Requires: gnome-boxes-license = %{version}-%{release}
Requires: gnome-boxes-locales = %{version}-%{release}
Requires: libosinfo
Requires: osinfo-db-tools
BuildRequires : appstream-glib
BuildRequires : buildreq-gnome
BuildRequires : buildreq-meson
BuildRequires : libarchive-dev
BuildRequires : libgudev-dev
BuildRequires : libosinfo
BuildRequires : libsoup-dev
BuildRequires : libusb-dev
BuildRequires : osinfo-db-tools
BuildRequires : pkgconfig(govirt-1.0)
BuildRequires : pkgconfig(gtk-vnc-2.0)
BuildRequires : pkgconfig(gudev-1.0)
BuildRequires : pkgconfig(libarchive)
BuildRequires : pkgconfig(libosinfo-1.0)
BuildRequires : pkgconfig(libsecret-1)
BuildRequires : pkgconfig(libsoup-2.4)
BuildRequires : pkgconfig(libusb-1.0)
BuildRequires : pkgconfig(libvirt-gconfig-1.0)
BuildRequires : pkgconfig(spice-client-gtk-3.0)
BuildRequires : pkgconfig(tracker-sparql-2.0)
BuildRequires : pkgconfig(vte-2.91)
BuildRequires : pkgconfig(webkit2gtk-4.0)
BuildRequires : pkgconfig(winpr2)
BuildRequires : spice-gtk
BuildRequires : spice-gtk-dev
BuildRequires : vte-dev
BuildRequires : webkitgtk-dev
Patch1: 0001-Add-Clear-Linux-as-recommended-distro.patch

%description
# This is the directory where we put upstream vapi bindings when they
# are outdated and we need a version with additional fixes.

%package bin
Summary: bin components for the gnome-boxes package.
Group: Binaries
Requires: gnome-boxes-data = %{version}-%{release}
Requires: gnome-boxes-libexec = %{version}-%{release}
Requires: gnome-boxes-license = %{version}-%{release}

%description bin
bin components for the gnome-boxes package.


%package data
Summary: data components for the gnome-boxes package.
Group: Data

%description data
data components for the gnome-boxes package.


%package dev
Summary: dev components for the gnome-boxes package.
Group: Development
Requires: gnome-boxes-lib = %{version}-%{release}
Requires: gnome-boxes-bin = %{version}-%{release}
Requires: gnome-boxes-data = %{version}-%{release}
Provides: gnome-boxes-devel = %{version}-%{release}
Requires: gnome-boxes = %{version}-%{release}

%description dev
dev components for the gnome-boxes package.


%package doc
Summary: doc components for the gnome-boxes package.
Group: Documentation

%description doc
doc components for the gnome-boxes package.


%package lib
Summary: lib components for the gnome-boxes package.
Group: Libraries
Requires: gnome-boxes-data = %{version}-%{release}
Requires: gnome-boxes-libexec = %{version}-%{release}
Requires: gnome-boxes-license = %{version}-%{release}

%description lib
lib components for the gnome-boxes package.


%package libexec
Summary: libexec components for the gnome-boxes package.
Group: Default
Requires: gnome-boxes-license = %{version}-%{release}

%description libexec
libexec components for the gnome-boxes package.


%package license
Summary: license components for the gnome-boxes package.
Group: Default

%description license
license components for the gnome-boxes package.


%package locales
Summary: locales components for the gnome-boxes package.
Group: Default

%description locales
locales components for the gnome-boxes package.


%prep
%setup -q -n gnome-boxes-3.34.3
cd %{_builddir}/gnome-boxes-3.34.3
%patch1 -p1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1580415187
export GCC_IGNORE_WERROR=1
export CFLAGS="$CFLAGS -fno-lto "
export FCFLAGS="$CFLAGS -fno-lto "
export FFLAGS="$CFLAGS -fno-lto "
export CXXFLAGS="$CXXFLAGS -fno-lto "
CFLAGS="$CFLAGS" CXXFLAGS="$CXXFLAGS" LDFLAGS="$LDFLAGS" meson --libdir=lib64 --prefix=/usr --buildtype=plain   builddir
ninja -v -C builddir

%install
mkdir -p %{buildroot}/usr/share/package-licenses/gnome-boxes
cp %{_builddir}/gnome-boxes-3.34.3/COPYING %{buildroot}/usr/share/package-licenses/gnome-boxes/ba8966e2473a9969bdcab3dc82274c817cfd98a1
cp %{_builddir}/gnome-boxes-3.34.3/copyright %{buildroot}/usr/share/package-licenses/gnome-boxes/a4c835de9e0708234c05f918157e7b47ac65cde7
cp %{_builddir}/gnome-boxes-3.34.3/subprojects/gtk-frdp/COPYING %{buildroot}/usr/share/package-licenses/gnome-boxes/a8a12e6867d7ee39c21d9b11a984066099b6fb6b
cp %{_builddir}/gnome-boxes-3.34.3/subprojects/libovf-glib/COPYING %{buildroot}/usr/share/package-licenses/gnome-boxes/3704f4680301a60004b20f94e0b5b8c7ff1484a9
DESTDIR=%{buildroot} ninja -C builddir install
%find_lang gnome-boxes

%files
%defattr(-,root,root,-)
/usr/lib64/gnome-boxes/girepository-1.0/Govf-0.1.typelib
/usr/lib64/gnome-boxes/girepository-1.0/GtkFrdp-0.1.typelib
/usr/lib64/gnome-boxes/pkgconfig/govf-0.1.pc
/usr/lib64/gnome-boxes/pkgconfig/gtk-frdp-0.1.pc

%files bin
%defattr(-,root,root,-)
/usr/bin/gnome-boxes

%files data
%defattr(-,root,root,-)
/usr/share/applications/org.gnome.Boxes.desktop
/usr/share/dbus-1/services/org.gnome.Boxes.SearchProvider.service
/usr/share/dbus-1/services/org.gnome.Boxes.service
/usr/share/glib-2.0/schemas/org.gnome.boxes.gschema.xml
/usr/share/gnome-boxes/gir-1.0/Govf-0.1.gir
/usr/share/gnome-boxes/gir-1.0/GtkFrdp-0.1.gir
/usr/share/gnome-boxes/osinfo/os/centos.org/centos-6.0.xml
/usr/share/gnome-boxes/osinfo/os/centos.org/centos-7.0.xml
/usr/share/gnome-boxes/osinfo/os/debian.org/debian-4.xml
/usr/share/gnome-boxes/osinfo/os/endlessos.com/eos-3.3.xml
/usr/share/gnome-boxes/osinfo/os/fedoraproject.org/fedora-1.xml
/usr/share/gnome-boxes/osinfo/os/fedoraproject.org/silverblue-28.xml
/usr/share/gnome-boxes/osinfo/os/freedos.org/freedos-1.2.xml
/usr/share/gnome-boxes/osinfo/os/opensuse.org/opensuse-10.2.xml
/usr/share/gnome-boxes/osinfo/os/redhat.com/rhel-4.0.xml
/usr/share/gnome-boxes/osinfo/os/redhat.com/rhel-5.0.xml
/usr/share/gnome-boxes/osinfo/os/redhat.com/rhel-6.0.xml
/usr/share/gnome-boxes/osinfo/os/redhat.com/rhel-7.0.xml
/usr/share/gnome-boxes/osinfo/os/redhat.com/rhel-8.0.xml
/usr/share/gnome-boxes/osinfo/os/system76.com/popos-17.10.xml
/usr/share/gnome-boxes/osinfo/os/ubuntu.com/ubuntu-4.10.xml
/usr/share/gnome-boxes/sources/QEMU_Session
/usr/share/gnome-boxes/unattended/disk.img
/usr/share/gnome-boxes/vapi/govf-0.1.deps
/usr/share/gnome-boxes/vapi/govf-0.1.vapi
/usr/share/gnome-boxes/vapi/gtk-frdp-0.1.deps
/usr/share/gnome-boxes/vapi/gtk-frdp-0.1.vapi
/usr/share/gnome-shell/search-providers/gnome-boxes-search-provider.ini
/usr/share/icons/hicolor/scalable/apps/org.gnome.Boxes.svg
/usr/share/icons/hicolor/symbolic/apps/org.gnome.Boxes-symbolic.svg
/usr/share/metainfo/org.gnome.Boxes.appdata.xml

%files dev
%defattr(-,root,root,-)
/usr/include/gnome-boxes/govf/govf-disk.h
/usr/include/gnome-boxes/govf/govf-package.h
/usr/include/gnome-boxes/govf/govf.h
/usr/include/gnome-boxes/gtk-frdp/frdp-display.h
/usr/include/gnome-boxes/gtk-frdp/frdp-session.h
/usr/include/gnome-boxes/gtk-frdp/gtk-frdp-version.h
/usr/include/gnome-boxes/gtk-frdp/gtk-frdp.h

%files doc
%defattr(0644,root,root,0755)
/usr/share/help/C/gnome-boxes/backup.page
/usr/share/help/C/gnome-boxes/clipboard.page
/usr/share/help/C/gnome-boxes/connect.page
/usr/share/help/C/gnome-boxes/create.page
/usr/share/help/C/gnome-boxes/delete.page
/usr/share/help/C/gnome-boxes/disk-images.page
/usr/share/help/C/gnome-boxes/figures/boxes_icon.png
/usr/share/help/C/gnome-boxes/figures/input-keyboard-symbolic.svg
/usr/share/help/C/gnome-boxes/figures/open-menu-symbolic.svg
/usr/share/help/C/gnome-boxes/index.page
/usr/share/help/C/gnome-boxes/interface.page
/usr/share/help/C/gnome-boxes/keystrokes.page
/usr/share/help/C/gnome-boxes/legal.xml
/usr/share/help/C/gnome-boxes/prop-system.page
/usr/share/help/C/gnome-boxes/prop-trouble.page
/usr/share/help/C/gnome-boxes/search.page
/usr/share/help/C/gnome-boxes/shared-folders.page
/usr/share/help/C/gnome-boxes/shortcuts.page
/usr/share/help/C/gnome-boxes/shutdown.page
/usr/share/help/C/gnome-boxes/snapshot-create.page
/usr/share/help/C/gnome-boxes/snapshot-delete.page
/usr/share/help/C/gnome-boxes/snapshot-rename.page
/usr/share/help/C/gnome-boxes/snapshot-revert.page
/usr/share/help/C/gnome-boxes/supported-protocols.page
/usr/share/help/C/gnome-boxes/system-requirements.page
/usr/share/help/C/gnome-boxes/usb-redirection.page
/usr/share/help/C/gnome-boxes/virtualization.page
/usr/share/help/C/gnome-boxes/what-is-a-virtual-machine.page
/usr/share/help/C/gnome-boxes/why-do-i-need-virtual-machine.page
/usr/share/help/cs/gnome-boxes/backup.page
/usr/share/help/cs/gnome-boxes/clipboard.page
/usr/share/help/cs/gnome-boxes/connect.page
/usr/share/help/cs/gnome-boxes/create.page
/usr/share/help/cs/gnome-boxes/delete.page
/usr/share/help/cs/gnome-boxes/disk-images.page
/usr/share/help/cs/gnome-boxes/figures/boxes_icon.png
/usr/share/help/cs/gnome-boxes/figures/input-keyboard-symbolic.svg
/usr/share/help/cs/gnome-boxes/figures/open-menu-symbolic.svg
/usr/share/help/cs/gnome-boxes/index.page
/usr/share/help/cs/gnome-boxes/interface.page
/usr/share/help/cs/gnome-boxes/keystrokes.page
/usr/share/help/cs/gnome-boxes/legal.xml
/usr/share/help/cs/gnome-boxes/prop-system.page
/usr/share/help/cs/gnome-boxes/prop-trouble.page
/usr/share/help/cs/gnome-boxes/search.page
/usr/share/help/cs/gnome-boxes/shared-folders.page
/usr/share/help/cs/gnome-boxes/shortcuts.page
/usr/share/help/cs/gnome-boxes/shutdown.page
/usr/share/help/cs/gnome-boxes/snapshot-create.page
/usr/share/help/cs/gnome-boxes/snapshot-delete.page
/usr/share/help/cs/gnome-boxes/snapshot-rename.page
/usr/share/help/cs/gnome-boxes/snapshot-revert.page
/usr/share/help/cs/gnome-boxes/supported-protocols.page
/usr/share/help/cs/gnome-boxes/system-requirements.page
/usr/share/help/cs/gnome-boxes/usb-redirection.page
/usr/share/help/cs/gnome-boxes/virtualization.page
/usr/share/help/cs/gnome-boxes/what-is-a-virtual-machine.page
/usr/share/help/cs/gnome-boxes/why-do-i-need-virtual-machine.page
/usr/share/help/de/gnome-boxes/backup.page
/usr/share/help/de/gnome-boxes/clipboard.page
/usr/share/help/de/gnome-boxes/connect.page
/usr/share/help/de/gnome-boxes/create.page
/usr/share/help/de/gnome-boxes/delete.page
/usr/share/help/de/gnome-boxes/disk-images.page
/usr/share/help/de/gnome-boxes/figures/boxes_icon.png
/usr/share/help/de/gnome-boxes/figures/input-keyboard-symbolic.svg
/usr/share/help/de/gnome-boxes/figures/open-menu-symbolic.svg
/usr/share/help/de/gnome-boxes/index.page
/usr/share/help/de/gnome-boxes/interface.page
/usr/share/help/de/gnome-boxes/keystrokes.page
/usr/share/help/de/gnome-boxes/legal.xml
/usr/share/help/de/gnome-boxes/prop-system.page
/usr/share/help/de/gnome-boxes/prop-trouble.page
/usr/share/help/de/gnome-boxes/search.page
/usr/share/help/de/gnome-boxes/shared-folders.page
/usr/share/help/de/gnome-boxes/shortcuts.page
/usr/share/help/de/gnome-boxes/shutdown.page
/usr/share/help/de/gnome-boxes/snapshot-create.page
/usr/share/help/de/gnome-boxes/snapshot-delete.page
/usr/share/help/de/gnome-boxes/snapshot-rename.page
/usr/share/help/de/gnome-boxes/snapshot-revert.page
/usr/share/help/de/gnome-boxes/supported-protocols.page
/usr/share/help/de/gnome-boxes/system-requirements.page
/usr/share/help/de/gnome-boxes/usb-redirection.page
/usr/share/help/de/gnome-boxes/virtualization.page
/usr/share/help/de/gnome-boxes/what-is-a-virtual-machine.page
/usr/share/help/de/gnome-boxes/why-do-i-need-virtual-machine.page
/usr/share/help/el/gnome-boxes/backup.page
/usr/share/help/el/gnome-boxes/clipboard.page
/usr/share/help/el/gnome-boxes/connect.page
/usr/share/help/el/gnome-boxes/create.page
/usr/share/help/el/gnome-boxes/delete.page
/usr/share/help/el/gnome-boxes/disk-images.page
/usr/share/help/el/gnome-boxes/figures/boxes_icon.png
/usr/share/help/el/gnome-boxes/figures/input-keyboard-symbolic.svg
/usr/share/help/el/gnome-boxes/figures/open-menu-symbolic.svg
/usr/share/help/el/gnome-boxes/index.page
/usr/share/help/el/gnome-boxes/interface.page
/usr/share/help/el/gnome-boxes/keystrokes.page
/usr/share/help/el/gnome-boxes/legal.xml
/usr/share/help/el/gnome-boxes/prop-system.page
/usr/share/help/el/gnome-boxes/prop-trouble.page
/usr/share/help/el/gnome-boxes/search.page
/usr/share/help/el/gnome-boxes/shared-folders.page
/usr/share/help/el/gnome-boxes/shortcuts.page
/usr/share/help/el/gnome-boxes/shutdown.page
/usr/share/help/el/gnome-boxes/snapshot-create.page
/usr/share/help/el/gnome-boxes/snapshot-delete.page
/usr/share/help/el/gnome-boxes/snapshot-rename.page
/usr/share/help/el/gnome-boxes/snapshot-revert.page
/usr/share/help/el/gnome-boxes/supported-protocols.page
/usr/share/help/el/gnome-boxes/system-requirements.page
/usr/share/help/el/gnome-boxes/usb-redirection.page
/usr/share/help/el/gnome-boxes/virtualization.page
/usr/share/help/el/gnome-boxes/what-is-a-virtual-machine.page
/usr/share/help/el/gnome-boxes/why-do-i-need-virtual-machine.page
/usr/share/help/es/gnome-boxes/backup.page
/usr/share/help/es/gnome-boxes/clipboard.page
/usr/share/help/es/gnome-boxes/connect.page
/usr/share/help/es/gnome-boxes/create.page
/usr/share/help/es/gnome-boxes/delete.page
/usr/share/help/es/gnome-boxes/disk-images.page
/usr/share/help/es/gnome-boxes/figures/boxes_icon.png
/usr/share/help/es/gnome-boxes/figures/input-keyboard-symbolic.svg
/usr/share/help/es/gnome-boxes/figures/open-menu-symbolic.svg
/usr/share/help/es/gnome-boxes/index.page
/usr/share/help/es/gnome-boxes/interface.page
/usr/share/help/es/gnome-boxes/keystrokes.page
/usr/share/help/es/gnome-boxes/legal.xml
/usr/share/help/es/gnome-boxes/prop-system.page
/usr/share/help/es/gnome-boxes/prop-trouble.page
/usr/share/help/es/gnome-boxes/search.page
/usr/share/help/es/gnome-boxes/shared-folders.page
/usr/share/help/es/gnome-boxes/shortcuts.page
/usr/share/help/es/gnome-boxes/shutdown.page
/usr/share/help/es/gnome-boxes/snapshot-create.page
/usr/share/help/es/gnome-boxes/snapshot-delete.page
/usr/share/help/es/gnome-boxes/snapshot-rename.page
/usr/share/help/es/gnome-boxes/snapshot-revert.page
/usr/share/help/es/gnome-boxes/supported-protocols.page
/usr/share/help/es/gnome-boxes/system-requirements.page
/usr/share/help/es/gnome-boxes/usb-redirection.page
/usr/share/help/es/gnome-boxes/virtualization.page
/usr/share/help/es/gnome-boxes/what-is-a-virtual-machine.page
/usr/share/help/es/gnome-boxes/why-do-i-need-virtual-machine.page
/usr/share/help/fr/gnome-boxes/backup.page
/usr/share/help/fr/gnome-boxes/clipboard.page
/usr/share/help/fr/gnome-boxes/connect.page
/usr/share/help/fr/gnome-boxes/create.page
/usr/share/help/fr/gnome-boxes/delete.page
/usr/share/help/fr/gnome-boxes/disk-images.page
/usr/share/help/fr/gnome-boxes/figures/boxes_icon.png
/usr/share/help/fr/gnome-boxes/figures/input-keyboard-symbolic.svg
/usr/share/help/fr/gnome-boxes/figures/open-menu-symbolic.svg
/usr/share/help/fr/gnome-boxes/index.page
/usr/share/help/fr/gnome-boxes/interface.page
/usr/share/help/fr/gnome-boxes/keystrokes.page
/usr/share/help/fr/gnome-boxes/legal.xml
/usr/share/help/fr/gnome-boxes/prop-system.page
/usr/share/help/fr/gnome-boxes/prop-trouble.page
/usr/share/help/fr/gnome-boxes/search.page
/usr/share/help/fr/gnome-boxes/shared-folders.page
/usr/share/help/fr/gnome-boxes/shortcuts.page
/usr/share/help/fr/gnome-boxes/shutdown.page
/usr/share/help/fr/gnome-boxes/snapshot-create.page
/usr/share/help/fr/gnome-boxes/snapshot-delete.page
/usr/share/help/fr/gnome-boxes/snapshot-rename.page
/usr/share/help/fr/gnome-boxes/snapshot-revert.page
/usr/share/help/fr/gnome-boxes/supported-protocols.page
/usr/share/help/fr/gnome-boxes/system-requirements.page
/usr/share/help/fr/gnome-boxes/usb-redirection.page
/usr/share/help/fr/gnome-boxes/virtualization.page
/usr/share/help/fr/gnome-boxes/what-is-a-virtual-machine.page
/usr/share/help/fr/gnome-boxes/why-do-i-need-virtual-machine.page
/usr/share/help/gl/gnome-boxes/backup.page
/usr/share/help/gl/gnome-boxes/clipboard.page
/usr/share/help/gl/gnome-boxes/connect.page
/usr/share/help/gl/gnome-boxes/create.page
/usr/share/help/gl/gnome-boxes/delete.page
/usr/share/help/gl/gnome-boxes/disk-images.page
/usr/share/help/gl/gnome-boxes/figures/boxes_icon.png
/usr/share/help/gl/gnome-boxes/figures/input-keyboard-symbolic.svg
/usr/share/help/gl/gnome-boxes/figures/open-menu-symbolic.svg
/usr/share/help/gl/gnome-boxes/index.page
/usr/share/help/gl/gnome-boxes/interface.page
/usr/share/help/gl/gnome-boxes/keystrokes.page
/usr/share/help/gl/gnome-boxes/legal.xml
/usr/share/help/gl/gnome-boxes/prop-system.page
/usr/share/help/gl/gnome-boxes/prop-trouble.page
/usr/share/help/gl/gnome-boxes/search.page
/usr/share/help/gl/gnome-boxes/shared-folders.page
/usr/share/help/gl/gnome-boxes/shortcuts.page
/usr/share/help/gl/gnome-boxes/shutdown.page
/usr/share/help/gl/gnome-boxes/snapshot-create.page
/usr/share/help/gl/gnome-boxes/snapshot-delete.page
/usr/share/help/gl/gnome-boxes/snapshot-rename.page
/usr/share/help/gl/gnome-boxes/snapshot-revert.page
/usr/share/help/gl/gnome-boxes/supported-protocols.page
/usr/share/help/gl/gnome-boxes/system-requirements.page
/usr/share/help/gl/gnome-boxes/usb-redirection.page
/usr/share/help/gl/gnome-boxes/virtualization.page
/usr/share/help/gl/gnome-boxes/what-is-a-virtual-machine.page
/usr/share/help/gl/gnome-boxes/why-do-i-need-virtual-machine.page
/usr/share/help/hu/gnome-boxes/backup.page
/usr/share/help/hu/gnome-boxes/clipboard.page
/usr/share/help/hu/gnome-boxes/connect.page
/usr/share/help/hu/gnome-boxes/create.page
/usr/share/help/hu/gnome-boxes/delete.page
/usr/share/help/hu/gnome-boxes/disk-images.page
/usr/share/help/hu/gnome-boxes/figures/boxes_icon.png
/usr/share/help/hu/gnome-boxes/figures/input-keyboard-symbolic.svg
/usr/share/help/hu/gnome-boxes/figures/open-menu-symbolic.svg
/usr/share/help/hu/gnome-boxes/index.page
/usr/share/help/hu/gnome-boxes/interface.page
/usr/share/help/hu/gnome-boxes/keystrokes.page
/usr/share/help/hu/gnome-boxes/legal.xml
/usr/share/help/hu/gnome-boxes/prop-system.page
/usr/share/help/hu/gnome-boxes/prop-trouble.page
/usr/share/help/hu/gnome-boxes/search.page
/usr/share/help/hu/gnome-boxes/shared-folders.page
/usr/share/help/hu/gnome-boxes/shortcuts.page
/usr/share/help/hu/gnome-boxes/shutdown.page
/usr/share/help/hu/gnome-boxes/snapshot-create.page
/usr/share/help/hu/gnome-boxes/snapshot-delete.page
/usr/share/help/hu/gnome-boxes/snapshot-rename.page
/usr/share/help/hu/gnome-boxes/snapshot-revert.page
/usr/share/help/hu/gnome-boxes/supported-protocols.page
/usr/share/help/hu/gnome-boxes/system-requirements.page
/usr/share/help/hu/gnome-boxes/usb-redirection.page
/usr/share/help/hu/gnome-boxes/virtualization.page
/usr/share/help/hu/gnome-boxes/what-is-a-virtual-machine.page
/usr/share/help/hu/gnome-boxes/why-do-i-need-virtual-machine.page
/usr/share/help/it/gnome-boxes/backup.page
/usr/share/help/it/gnome-boxes/clipboard.page
/usr/share/help/it/gnome-boxes/connect.page
/usr/share/help/it/gnome-boxes/create.page
/usr/share/help/it/gnome-boxes/delete.page
/usr/share/help/it/gnome-boxes/disk-images.page
/usr/share/help/it/gnome-boxes/figures/boxes_icon.png
/usr/share/help/it/gnome-boxes/figures/input-keyboard-symbolic.svg
/usr/share/help/it/gnome-boxes/figures/open-menu-symbolic.svg
/usr/share/help/it/gnome-boxes/index.page
/usr/share/help/it/gnome-boxes/interface.page
/usr/share/help/it/gnome-boxes/keystrokes.page
/usr/share/help/it/gnome-boxes/legal.xml
/usr/share/help/it/gnome-boxes/prop-system.page
/usr/share/help/it/gnome-boxes/prop-trouble.page
/usr/share/help/it/gnome-boxes/search.page
/usr/share/help/it/gnome-boxes/shared-folders.page
/usr/share/help/it/gnome-boxes/shortcuts.page
/usr/share/help/it/gnome-boxes/shutdown.page
/usr/share/help/it/gnome-boxes/snapshot-create.page
/usr/share/help/it/gnome-boxes/snapshot-delete.page
/usr/share/help/it/gnome-boxes/snapshot-rename.page
/usr/share/help/it/gnome-boxes/snapshot-revert.page
/usr/share/help/it/gnome-boxes/supported-protocols.page
/usr/share/help/it/gnome-boxes/system-requirements.page
/usr/share/help/it/gnome-boxes/usb-redirection.page
/usr/share/help/it/gnome-boxes/virtualization.page
/usr/share/help/it/gnome-boxes/what-is-a-virtual-machine.page
/usr/share/help/it/gnome-boxes/why-do-i-need-virtual-machine.page
/usr/share/help/ko/gnome-boxes/backup.page
/usr/share/help/ko/gnome-boxes/clipboard.page
/usr/share/help/ko/gnome-boxes/connect.page
/usr/share/help/ko/gnome-boxes/create.page
/usr/share/help/ko/gnome-boxes/delete.page
/usr/share/help/ko/gnome-boxes/disk-images.page
/usr/share/help/ko/gnome-boxes/figures/boxes_icon.png
/usr/share/help/ko/gnome-boxes/figures/input-keyboard-symbolic.svg
/usr/share/help/ko/gnome-boxes/figures/open-menu-symbolic.svg
/usr/share/help/ko/gnome-boxes/index.page
/usr/share/help/ko/gnome-boxes/interface.page
/usr/share/help/ko/gnome-boxes/keystrokes.page
/usr/share/help/ko/gnome-boxes/legal.xml
/usr/share/help/ko/gnome-boxes/prop-system.page
/usr/share/help/ko/gnome-boxes/prop-trouble.page
/usr/share/help/ko/gnome-boxes/search.page
/usr/share/help/ko/gnome-boxes/shared-folders.page
/usr/share/help/ko/gnome-boxes/shortcuts.page
/usr/share/help/ko/gnome-boxes/shutdown.page
/usr/share/help/ko/gnome-boxes/snapshot-create.page
/usr/share/help/ko/gnome-boxes/snapshot-delete.page
/usr/share/help/ko/gnome-boxes/snapshot-rename.page
/usr/share/help/ko/gnome-boxes/snapshot-revert.page
/usr/share/help/ko/gnome-boxes/supported-protocols.page
/usr/share/help/ko/gnome-boxes/system-requirements.page
/usr/share/help/ko/gnome-boxes/usb-redirection.page
/usr/share/help/ko/gnome-boxes/virtualization.page
/usr/share/help/ko/gnome-boxes/what-is-a-virtual-machine.page
/usr/share/help/ko/gnome-boxes/why-do-i-need-virtual-machine.page
/usr/share/help/pl/gnome-boxes/backup.page
/usr/share/help/pl/gnome-boxes/clipboard.page
/usr/share/help/pl/gnome-boxes/connect.page
/usr/share/help/pl/gnome-boxes/create.page
/usr/share/help/pl/gnome-boxes/delete.page
/usr/share/help/pl/gnome-boxes/disk-images.page
/usr/share/help/pl/gnome-boxes/figures/boxes_icon.png
/usr/share/help/pl/gnome-boxes/figures/input-keyboard-symbolic.svg
/usr/share/help/pl/gnome-boxes/figures/open-menu-symbolic.svg
/usr/share/help/pl/gnome-boxes/index.page
/usr/share/help/pl/gnome-boxes/interface.page
/usr/share/help/pl/gnome-boxes/keystrokes.page
/usr/share/help/pl/gnome-boxes/legal.xml
/usr/share/help/pl/gnome-boxes/prop-system.page
/usr/share/help/pl/gnome-boxes/prop-trouble.page
/usr/share/help/pl/gnome-boxes/search.page
/usr/share/help/pl/gnome-boxes/shared-folders.page
/usr/share/help/pl/gnome-boxes/shortcuts.page
/usr/share/help/pl/gnome-boxes/shutdown.page
/usr/share/help/pl/gnome-boxes/snapshot-create.page
/usr/share/help/pl/gnome-boxes/snapshot-delete.page
/usr/share/help/pl/gnome-boxes/snapshot-rename.page
/usr/share/help/pl/gnome-boxes/snapshot-revert.page
/usr/share/help/pl/gnome-boxes/supported-protocols.page
/usr/share/help/pl/gnome-boxes/system-requirements.page
/usr/share/help/pl/gnome-boxes/usb-redirection.page
/usr/share/help/pl/gnome-boxes/virtualization.page
/usr/share/help/pl/gnome-boxes/what-is-a-virtual-machine.page
/usr/share/help/pl/gnome-boxes/why-do-i-need-virtual-machine.page
/usr/share/help/pt_BR/gnome-boxes/backup.page
/usr/share/help/pt_BR/gnome-boxes/clipboard.page
/usr/share/help/pt_BR/gnome-boxes/connect.page
/usr/share/help/pt_BR/gnome-boxes/create.page
/usr/share/help/pt_BR/gnome-boxes/delete.page
/usr/share/help/pt_BR/gnome-boxes/disk-images.page
/usr/share/help/pt_BR/gnome-boxes/figures/boxes_icon.png
/usr/share/help/pt_BR/gnome-boxes/figures/input-keyboard-symbolic.svg
/usr/share/help/pt_BR/gnome-boxes/figures/open-menu-symbolic.svg
/usr/share/help/pt_BR/gnome-boxes/index.page
/usr/share/help/pt_BR/gnome-boxes/interface.page
/usr/share/help/pt_BR/gnome-boxes/keystrokes.page
/usr/share/help/pt_BR/gnome-boxes/legal.xml
/usr/share/help/pt_BR/gnome-boxes/prop-system.page
/usr/share/help/pt_BR/gnome-boxes/prop-trouble.page
/usr/share/help/pt_BR/gnome-boxes/search.page
/usr/share/help/pt_BR/gnome-boxes/shared-folders.page
/usr/share/help/pt_BR/gnome-boxes/shortcuts.page
/usr/share/help/pt_BR/gnome-boxes/shutdown.page
/usr/share/help/pt_BR/gnome-boxes/snapshot-create.page
/usr/share/help/pt_BR/gnome-boxes/snapshot-delete.page
/usr/share/help/pt_BR/gnome-boxes/snapshot-rename.page
/usr/share/help/pt_BR/gnome-boxes/snapshot-revert.page
/usr/share/help/pt_BR/gnome-boxes/supported-protocols.page
/usr/share/help/pt_BR/gnome-boxes/system-requirements.page
/usr/share/help/pt_BR/gnome-boxes/usb-redirection.page
/usr/share/help/pt_BR/gnome-boxes/virtualization.page
/usr/share/help/pt_BR/gnome-boxes/what-is-a-virtual-machine.page
/usr/share/help/pt_BR/gnome-boxes/why-do-i-need-virtual-machine.page
/usr/share/help/sv/gnome-boxes/backup.page
/usr/share/help/sv/gnome-boxes/clipboard.page
/usr/share/help/sv/gnome-boxes/connect.page
/usr/share/help/sv/gnome-boxes/create.page
/usr/share/help/sv/gnome-boxes/delete.page
/usr/share/help/sv/gnome-boxes/disk-images.page
/usr/share/help/sv/gnome-boxes/figures/boxes_icon.png
/usr/share/help/sv/gnome-boxes/figures/input-keyboard-symbolic.svg
/usr/share/help/sv/gnome-boxes/figures/open-menu-symbolic.svg
/usr/share/help/sv/gnome-boxes/index.page
/usr/share/help/sv/gnome-boxes/interface.page
/usr/share/help/sv/gnome-boxes/keystrokes.page
/usr/share/help/sv/gnome-boxes/legal.xml
/usr/share/help/sv/gnome-boxes/prop-system.page
/usr/share/help/sv/gnome-boxes/prop-trouble.page
/usr/share/help/sv/gnome-boxes/search.page
/usr/share/help/sv/gnome-boxes/shared-folders.page
/usr/share/help/sv/gnome-boxes/shortcuts.page
/usr/share/help/sv/gnome-boxes/shutdown.page
/usr/share/help/sv/gnome-boxes/snapshot-create.page
/usr/share/help/sv/gnome-boxes/snapshot-delete.page
/usr/share/help/sv/gnome-boxes/snapshot-rename.page
/usr/share/help/sv/gnome-boxes/snapshot-revert.page
/usr/share/help/sv/gnome-boxes/supported-protocols.page
/usr/share/help/sv/gnome-boxes/system-requirements.page
/usr/share/help/sv/gnome-boxes/usb-redirection.page
/usr/share/help/sv/gnome-boxes/virtualization.page
/usr/share/help/sv/gnome-boxes/what-is-a-virtual-machine.page
/usr/share/help/sv/gnome-boxes/why-do-i-need-virtual-machine.page

%files lib
%defattr(-,root,root,-)
/usr/lib64/gnome-boxes/libgovf-0.1.so
/usr/lib64/gnome-boxes/libgtk-frdp-0.1.so

%files libexec
%defattr(-,root,root,-)
/usr/libexec/gnome-boxes-search-provider

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/gnome-boxes/3704f4680301a60004b20f94e0b5b8c7ff1484a9
/usr/share/package-licenses/gnome-boxes/a4c835de9e0708234c05f918157e7b47ac65cde7
/usr/share/package-licenses/gnome-boxes/a8a12e6867d7ee39c21d9b11a984066099b6fb6b
/usr/share/package-licenses/gnome-boxes/ba8966e2473a9969bdcab3dc82274c817cfd98a1

%files locales -f gnome-boxes.lang
%defattr(-,root,root,-)

