#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : gnome-boxes
Version  : 43.0
Release  : 37
URL      : https://download.gnome.org/sources/gnome-boxes/43/gnome-boxes-43.0.tar.xz
Source0  : https://download.gnome.org/sources/gnome-boxes/43/gnome-boxes-43.0.tar.xz
Summary  : Library for reading and writing virtual machine images in the Open Virtualization Format
Group    : Development/Tools
License  : CC-BY-2.0 LGPL-2.0 LGPL-2.1
Requires: libosinfo
Requires: osinfo-db-tools
BuildRequires : appstream-glib
BuildRequires : buildreq-gnome
BuildRequires : buildreq-meson
BuildRequires : libarchive-dev
BuildRequires : libgudev-dev
BuildRequires : libhandy-dev
BuildRequires : libsoup-dev
BuildRequires : libusb-dev
BuildRequires : pkgconfig(gtk-vnc-2.0)
BuildRequires : pkgconfig(gtksourceview-4)
BuildRequires : pkgconfig(gudev-1.0)
BuildRequires : pkgconfig(libarchive)
BuildRequires : pkgconfig(libosinfo-1.0)
BuildRequires : pkgconfig(libsecret-1)
BuildRequires : pkgconfig(libsoup-3.0)
BuildRequires : pkgconfig(libusb-1.0)
BuildRequires : pkgconfig(libvirt-gconfig-1.0)
BuildRequires : pkgconfig(tracker-sparql-3.0)
BuildRequires : pkgconfig(vte-2.91)
BuildRequires : pkgconfig(webkit2gtk-4.1)
BuildRequires : pkgconfig(winpr2)
BuildRequires : spice-gtk
BuildRequires : spice-gtk-dev
BuildRequires : vte-dev
Patch1: 0001-Add-Clear-Linux-as-recommended-distro.patch
Patch2: backport-Port-to-libsoup-3.patch
Patch3: backport-build-flatpak-Bump-libosinfo-to-1.10.0.patch
Patch4: backport-downloader-Disable-network-test-before-download-star.patch

%description
# This is the directory where we put upstream vapi bindings when they
# are outdated and we need a version with additional fixes.

%prep
%setup -q -n gnome-boxes-43.0
cd %{_builddir}/gnome-boxes-43.0
%patch1 -p1
%patch2 -p1
%patch3 -p1
%patch4 -p1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1663965761
export GCC_IGNORE_WERROR=1
export CFLAGS="$CFLAGS -fno-lto "
export FCFLAGS="$FFLAGS -fno-lto "
export FFLAGS="$FFLAGS -fno-lto "
export CXXFLAGS="$CXXFLAGS -fno-lto "
CFLAGS="$CFLAGS" CXXFLAGS="$CXXFLAGS" LDFLAGS="$LDFLAGS" meson --libdir=lib64 --prefix=/usr --buildtype=plain   builddir
ninja -v -C builddir

%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
meson test -C builddir --print-errorlogs || :

%install
mkdir -p %{buildroot}/usr/share/package-licenses/gnome-boxes
cp %{_builddir}/gnome-boxes-%{version}/COPYING %{buildroot}/usr/share/package-licenses/gnome-boxes/ba8966e2473a9969bdcab3dc82274c817cfd98a1 || :
cp %{_builddir}/gnome-boxes-%{version}/copyright %{buildroot}/usr/share/package-licenses/gnome-boxes/a4c835de9e0708234c05f918157e7b47ac65cde7 || :
cp %{_builddir}/gnome-boxes-%{version}/subprojects/libovf-glib/COPYING %{buildroot}/usr/share/package-licenses/gnome-boxes/3704f4680301a60004b20f94e0b5b8c7ff1484a9 || :
DESTDIR=%{buildroot} ninja -C builddir install

%files
%defattr(-,root,root,-)
